### ISSUE TITLE
Package titles don't match apt package names

### ISSUE THREAD

**Issue by oskarpearson** [mediasuitenz/ansible-dokku#1]
Hi

https://github.com/mediasuitenz/ansible-dokku/blob/master/roles/dependencies/tasks/main.yml appears to have some copy-and-paste errors. The name 'git' matches in the first case, but in all the other cases the name is only set in the comment.

This is ok:

```
- name: install git
  apt: "name=git state=latest update_cache=yes"
```

This isn't since it should be "apt: name=man-db" instead of "apt: name=git"

```
- name: install man-db
  apt: "name=git state=latest update_cache=yes"
```

Also note that it's much faster to do this, since ansible will install all items with one apt command, rather than running apt-get install multiple times:

```
- name: Install requirements
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - man-db
    ...
```
